input_dir: "input/originals"
output_display_dir: "output/display"
output_thumb_dir: "output/thumbs"
output_metadata_dir: "output/metadata"
output_logs_dir: "output/logs"

thumb_max_size: 800
display_max_size: 2400

thumb_quality: 75
display_quality: 85

supported_extensions:
  - ".jpg"
  - ".jpeg"
  - ".png"

default_author: "Luke Chu"

overwrite: false

# ===== AI metadata generation =====
qwen_model_path: "C:/Users/Luke/.cache/modelscope/hub/models/Qwen/Qwen3-VL-4B-Instruct"
qwen_processor_path: "C:/Users/Luke/.cache/modelscope/hub/models/Qwen/Qwen3-VL-4B-Instruct"

ai_prompt_file: "prompts/photo_metadata_prompt.txt"

ai_input_jsonl: "output/metadata/photos.jsonl"
ai_output_jsonl: "output/metadata/photos_ai.jsonl"
ai_failed_jsonl: "output/metadata/photos_ai_failed.jsonl"

# 使用 thumb 图做识别，更快、更省显存
ai_image_source: "thumb"

# 是否跳过已经有 title_cn 的记录
ai_skip_completed: true

# 推理参数
ai_max_new_tokens: 256
ai_temperature: 0.2
ai_top_p: 0.9
ai_do_sample: false

# 断点续跑
ai_resume: true

# prompt 版本号，便于后面区分
ai_prompt_version: "v1"